version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - referral_network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - referral_network
    depends_on:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: referral
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    networks:
      - referral_network

  redis:
    image: redis:latest
    networks:
      - referral_network

  celery:
    build: .
    command: ["celery", "-A", "referral_system", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - referral_network

networks:
  referral_network:
    driver: bridge
